-- 코드를 입력하세요
-- 완료된 중고 거래의 총금액이 70만원 이상
-- 회원 ID, 닉네임, 총거래금액(오름차순)
SELECT BOARD.WRITER_ID AS USER_ID, USER.NICKNAME AS NICKNAME, SUM(BOARD.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS BOARD
LEFT JOIN USED_GOODS_USER AS USER ON USER.USER_ID = BOARD.WRITER_ID
WHERE BOARD.STATUS = 'DONE'
GROUP BY BOARD.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC